### ISSUE TITLE
NullPointerException in FileSpanningOutputStream 

### ISSUE THREAD

**Issue by mgocode** [mgocode/izpack#2]
NullPointerException in FileSpanningOutputStream when building installer using MultiVolumePackager. 

Only happens with logging level >= fine, which is why it does not show in unit tests.

---
Writing 9 Packs into installer
   [izpack] Exception in thread "Thread-3" java.lang.NullPointerException
   [izpack]     at com.izforge.izpack.ant.IzpackAntRunnable.run(IzpackAntRunnable.java:82)
   [izpack]     at java.lang.Thread.run(Thread.java:748)
   [izpack] Caused by: java.lang.NullPointerException
   [izpack]     at com.izforge.izpack.core.io.FileSpanningOutputStream.formatMagic(FileSpanningOutputStream.java:218)
   [izpack]     at com.izforge.izpack.core.io.FileSpanningOutputStream$SpanningOutputStream.generateMagicNumber(FileSpanningOutputStream.java:398)
   [izpack]     at com.izforge.izpack.core.io.FileSpanningOutputStream$SpanningOutputStream.<init>(FileSpanningOutputStream.java:283)
   [izpack]     at com.izforge.izpack.core.io.FileSpanningOutputStream.<init>(FileSpanningOutputStream.java:129)
   [izpack]     at com.izforge.izpack.compiler.packager.impl.MultiVolumePackager.writePacks(MultiVolumePackager.java:220)
   [izpack]     at com.izforge.izpack.compiler.packager.impl.MultiVolumePackager.writePacks(MultiVolumePackager.java:190)
   [izpack]     at com.izforge.izpack.compiler.packager.impl.PackagerBase.writeInstaller(PackagerBase.java:424)
   [izpack]     at com.izforge.izpack.compiler.packager.impl.PackagerBase.createInstaller(PackagerBase.java:354)
   [izpack]     at com.izforge.izpack.compiler.Compiler.createInstaller(Compiler.java:161)
   [izpack]     at com.izforge.izpack.compiler.CompilerConfig.executeCompiler(CompilerConfig.java:365)
   [izpack]     at com.izforge.izpack.ant.IzpackAntRunnable.run(IzpackAntRunnable.java:78)

**Comment by mgocode** [comment]
Done.
